# Generated by Django 3.2.4 on 2021-06-25 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_conversation_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date and time sent'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date and time sent'),
        ),
    ]
