# Generated by Django 3.2.4 on 2021-06-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210625_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date and time sent'),
        ),
        migrations.AlterField(
            model_name='thought',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date and time sent'),
        ),
    ]
